#!/bin/bash

#ARGUMENTS 

#Standard arguments:

WORKDIR=$1 #DIR containing all data directories (make sure to remove the ending backspace)
SCRIPT=$2 #Script to be called

#Options available:
 # Full functional pre-processing to connectome construction 
 # Functional connectome construction only

#Extra Arguments - script specific options
nargs=$#
extargs=${@:3}

find $1/* -maxdepth 0 -type d > ${WORKDIR}/scans.txt #Creates list of folders containing the subject data to be analysed

pipedir=$(pwd)
#PATH=$PATH$( find $pipedir/ -type d -printf ":%p" )

#Convert base script into subject specific batch jobs

mkdir ${WORKDIR}/batch

while read line
do
	Sess=$(basename $line)
	SessDIRECTORY=$line
	cp dtiblank ${WORKDIR}/batch/${SCRIPT}_$Sess.sh
	sed -i "s;&&&&;$pipedir;" ${WORKDIR}/batch/${SCRIPT}_$Sess.sh
	sed -i "s/@@@@/$Sess/" ${WORKDIR}/batch/${SCRIPT}_$Sess.sh
	sed -i "s!????!$SessDIRECTORY!" ${WORKDIR}/batch/${SCRIPT}_$Sess.sh
	sed -i "s:%%%%:$SCRIPT $Sess $WORKDIR $extargs:" ${WORKDIR}/batch/${SCRIPT}_$Sess.sh

done < ${WORKDIR}/scans.txt #List of folders containing each subject data to be analysed
