#!/bin/sh

bash /opt/ANTs/Scripts/antsBrainExtraction.sh -d 3 -a sub-030_T1w.nii -e neurobattery-template/PTBP/PTBP_T1_Defaced.nii.gz -m neurobattery-template/PTBP/PTBP_T1_BrainCerebellumProbabilityMask.nii.gz -o sub030

bash /opt/ANTs/Scripts/antsBrainExtraction.sh -d 3 -a sub-011_T1w.nii -e neurobattery-template/PTBP/PTBP_T1_Defaced.nii.gz -m neurobattery-template/PTBP/PTBP_T1_BrainCerebellumProbabilityMask.nii.gz -o sub011


antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [antssub011to030,antssub011to030Warped.nii.gz,antssub011to030InverseWarped.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [sub030BrainExtractionBrain.nii.gz,sub011BrainExtractionBrain.nii.gz,1] --transform Rigid[0.1] --metric MI[sub030BrainExtractionBrain.nii.gz,sub011BrainExtractionBrain.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x0,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox --transform Affine[0.1] --metric MI[sub030BrainExtractionBrain.nii.gz,sub011BrainExtractionBrain.nii.gz,1,32,Regular,0.25] --convergence [1000x500x250x0,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

c3d_affine_tool -ref antssub011to030Warped.nii.gz -src sub11BrainExtractionBrain.nii.gz -itk antssub11to300GenericAffine.mat -ras2fsl -o sub11to30-fsl.mat
