#!/bin/bash
# file: connectome_only
# usage: connectome_only Sess WORKDIR Parc Parcname

# note: for only after preprocessing with fmriprep and scripts here have been performed..

Sess=$1
WORKDIR=$2

Parc=$3
Parcname=$4

cd ${WORKDIR}/functional/${Sess}/func
SessDIR=${WORKDIR}/functional/${Sess}/func

#Extacted timeseries from parcellation region means

fslmeants -i ${SessDIR}/preproc/sub-01_${Sess}_task-rest_run-001_bold_space-T1w_preproc_regressed_smoothed_filtered.nii.gz --label=${Parc} > ${SessDIR}/preproc/sub-01_${Sess}_task-rest_run-001_bold_space-T1w_preprocfull_${Parcname}_timeseries.txt
