#!/bin/bash
#file : segparcT1
#usage: segparcT1 <subj> <WORKDIR> parctype PRESEGDIR(optional)

#FSparctype options = "DES" (desikan, 68 rois) or DST (destrieux; 148)


subj=$1
WORKDIR=$2
AnatPrepDir=$3
FSsubj=$4

subjAnatPrepDir=${WORKDIR}/${AnatPrepDir}/${FSsubj}

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi

SUBJECTS_DIR=${WORKDIR}/FS

#subjAnatPrepDir=${WORKDIR}/${AnatPrepDir}/${FSsubj}

#Prepare


#Coregistrations setup

bbregister --s $FSsubj --mov meanbiasb5shellbet.nii.gz --init-fsl --reg register.dat --dti --fslmat diff2FS.mat

transformconvert diff2FS.mat meanbiasb5shellbet.nii.gz $SUBJECTS_DIR/$FSsubj/mri/brain.mgz flirt_import diff2FSMR.mat -force

mrtransform $SUBJECTS_DIR/$FSsubj/mri/brain.mgz rFS.nii -linear diff2FSMR.mat -inverse -force

mrtransform $SUBJECTS_DIR/$FSsubj/mri/brain.mgz rFSrg.nii -linear diff2FSMR.mat -inverse -template fa.nii -force

mrconvert rFSrg.nii rFSrgstr.nii -stride +1,2,3 -nthreads $ncpus -force

mv rFSrgstr.nii rFSrg.nii


#Move other files from T1 space into Diff

mrtransform ${subjAnatPrepDir}/5TTFSspgmwmi.nii r5TTgmwmi.nii -linear diff2FSMR.mat -inverse -force

mrtransform ${subjAnatPrepDir}/5TTFSspmasked.nii r5TT.nii -linear diff2FSMR.mat -inverse -force


convert_xfm -omat FS2diff.mat -inverse diff2FS.mat

flirt -ref fa.nii -in ${subjAnatPrepDir}/parc_fixsubcortFS.nii.gz -applyxfm -init FS2diff.mat -out rparc_fixsubcort.nii.gz  -interp nearestneighbour

gunzip -f rparc_fixsubcort.nii.gz
