#!/bin/bash
#file : segparcT1
#usage: segparcT1 <subj> <WORKDIR> CATSEGDIR(optional)

subj=$1
WORKDIR=$2
CATSEGDIR=$3


mkdir -p $WORKDIR/AnatPrep/${subj}
cd $WORKDIR/AnatPrep/${subj}

SUBJECTS_DIR=${WORKDIR}/FS

if [ -n "$3" ]; then
echo "SEGMENTATION HAS ALREADY BEEN PERFORMED"

subjCATSEGDIR=${WORKDIR}/${CATSEGDIR}/${subj}

echo "Subject segmentations located in ${subjCATSEGDIR}"

fi

#prepare anatomical volume for segmentation, parcellation correction

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFS.nii -stride +1,2,3 -nthreads $ncpus -force

mrconvert $SUBJECTS_DIR/$subj/mri/T1.mgz FS.nii -nthreads $ncpus -force

rsync /working/lab_michaebr/alistaiP/poldrack/myconnectomedata/Raw/${subj}/T1.nii .

bet2  T1.nii T1bet -f 0.15

mrconvert $SUBJECTS_DIR/$subj/mri/brain.mgz brainFSsp.nii -nthreads $ncpus -force

flirt -ref T1bet.nii.gz -in brainFSsp.nii -dof 6 -out FS2FSL -omat FS2FSL.mat

convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

bet2 FS2FSL.nii.gz FS2FSLbet -f 0.15 -m

fslmaths T1bet.nii.gz -mas FS2FSLbet_mask.nii.gz T1betFSmasked.nii.gz


fast -B --nopve T1betFSmasked.nii.gz

#5ttgen fsl T1betFSmasked.nii.gz -nocrop -premasked -sgm_amyg_hipp 5TTfsl.nii -nthreads $ncpus -force -tempdir . -nocleanup

if [ -n "$3" ]; then
echo "SEGMENTATION already performed | expect tissues to have filenames: GM.nii WM.nii CSF.nii"

5ttgen_manual T1betFSmasked.nii.gz 5TT.nii $subjCATSEGDIR

else

5ttgen fsl T1betFSmasked.nii.gz 5TT.nii -premasked -nocrop -sgm_amyg_hipp -force -nocleanup -nthreads $ncpus -tempdir .

fi

5tt2gmwmi 5TT.nii 5TTgmwmi.nii -nthreads $ncpus -force

labelconvert $SUBJECTS_DIR/$subj/mri/aparc.a2009s+aseg.mgz $FREESURFER_HOME/FreeSurferColorLUT.txt $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc.nii -nthreads $ncpus -force

flirt -ref T1bet.nii.gz -in parc.nii -applyxfm -init FS2FSL.mat -interp nearestneighbour -out parcFSL.nii.gz

rm parc_fixsubcort.nii

mrconvert parcFSL.nii.gz parcFSLtempstr.nii.gz -stride -1,2,3 -force -nthreads $ncpus

labelsgmfix parcFSLtempstr.nii.gz T1betFSmasked_restore.nii.gz $MRTRIX/share/mrtrix3/labelconvert/fs_a2009s.txt parc_fixsubcort.nii -sgm_amyg_hipp -premasked -nthreads $ncpus -force

mrconvert parc_fixsubcort.nii parc_fixsubcortstr.nii -stride +1,2,3 -force -nthreads $ncpus

mv parc_fixsubcortstr.nii parc_fixsubcort.nii

rm parcFSLtempstr.nii.gz


#Coregistrations setup



#Move other files from T1 space

transformconvert FS2FSL.mat brainFSsp.nii T1bet.nii.gz flirt_import FS2FSLMR.mat -force -nthreads $ncpus

mrtransform 5TT.nii 5TTFSspmasked.nii -linear FS2FSLMR.mat -inverse -force -nthreads $ncpus

mrtransform 5TTgmwmi.nii 5TTFSspgmwmi.nii -linear FS2FSLMR.mat -inverse -force -nthreads $ncpus


#Now into diff


convert_xfm -omat FSL2FS.mat -inverse FS2FSL.mat

flirt -ref brainFSsp.nii -in parc_fixsubcort.nii -applyxfm -init FSL2FS.mat -interp nearestneighbour -out parc_fixsubcortFS.nii.gz


