#!/bin/bash
#file : segparcT1
#usage: segparcT1 <subj> <WORKDIR> AnatPrepDir

#FSparctype options = "DES" (desikan, 68 rois) or DST (destrieux; 148)


subj=$1
WORKDIR=$2
AnatPrepDir=$3

subjAnatPrepDir=${WORKDIR}/${AnatPrepDir}
subjFSDir=${WORKDIR}/${AnatPrepDir}/FS/sub-01
SUBJECTS_DIR=${WORKDIR}/${AnatPrepDir}/FS

rundir=$(pwd)
baserundir=$(basename $rundir)

if [ "$rundir" != "$WORKDIR/Diff/$subj/preproc" ]; then
cd $WORKDIR/Diff/$subj/preproc
fi


#Coregistrations setup

bbregister --s sub-01 --mov biasmeanb0bet.nii.gz --init-fsl --reg register.dat --dti --fslmat diff2FS.mat

transformconvert diff2FS.mat biasmeanb0bet.nii.gz $SUBJECTS_DIR/sub-01/mri/brain.mgz flirt_import diff2FSMR.mat -force

mrtransform $SUBJECTS_DIR/sub-01/mri/brain.mgz rFS.nii -linear diff2FSMR.mat -inverse -force

mrtransform $SUBJECTS_DIR/sub-01/mri/brain.mgz rFSrg.nii -linear diff2FSMR.mat -inverse -template fa.nii -force

mrconvert rFSrg.nii rFSrgstr.nii -stride +1,2,3 -nthreads $ncpus -force

mv rFSrgstr.nii rFSrg.nii


#Move other files from T1 space into Diff

mrtransform ${subjAnatPrepDir}/5TTFSspgmwmi.nii r5TTgmwmi.nii -linear diff2FSMR.mat -inverse -force

mrtransform ${subjAnatPrepDir}/5TTFSspmasked.nii r5TT.nii -linear diff2FSMR.mat -inverse -force


convert_xfm -omat FS2diff.mat -inverse diff2FS.mat

flirt -ref fa.nii -in ${subjAnatPrepDir}/parcFS_fixsubcort.nii -applyxfm -init FS2diff.mat -out rparc_fixsubcort.nii.gz  -interp nearestneighbour

gunzip -f rparc_fixsubcort.nii.gz
